title: Project WorkFlow With Kingsley
author: sterlingking1990.github.io
email: izundukingsleyemeka@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is a mini overview of my experience with github flow, the possibilities
 we can have using it across various sectors and usecases. I hope you enjoy!

# social links
twitter_username: semantiking # DO NOT include the @ character, or else the build will fail!
github_username:  sterlingking1990 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
